[package]
name = "codejam2021"
version = "0.1.0"
authors = ["tanguy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.2.1"