[package]
name = "Round_A1"
version = "0.1.0"
authors = ["Tanguy Mazé <tmaze@student.42.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
